name: pixl.js-fw

on:
  push:
    branches: [ "develop", "neo_v2", "kr_db_v1"]
    tags:  ["*"]
  pull_request:
    types: ["opened"]
    branches: ["develop"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        board: ["LCD", "OLED"]
    runs-on: ubuntu-latest
    container: solosky/nrf52-sdk:latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Change Owner of Container Working Directory
      run: chown root:root .
    - name: build firmware
      run: |
        cd fw
        python3 scripts/font_data_gen.py
        make all RELEASE=1 APP_VERSION=19 BOARD=${{matrix.board}}
    - name: copy artifact
      run: mv fw/_build/bootloader.hex . && mv fw/_build/pixljs.hex . && mv fw/_build/pixljs_all.hex . && mv fw/_build/pixjs_ota_v19.zip . && mv fw/docs/fw_readme.txt . && mv  fw/scripts/fw_update.bat .
    - name: rename files for board
      run: |
        mv pixljs_all.hex pixljs_all_${{matrix.board}}.hex
        mv pixjs_ota_v19.zip pixjs_ota_v19_${{matrix.board}}.zip
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pixljs_fw_${{matrix.board}}
        path: |
          bootloader.hex
          pixljs.hex
          pixljs_all_${{matrix.board}}.hex
          pixjs_ota_v19_${{matrix.board}}.zip
          fw_readme.txt
          fw_update.bat
    - name: create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{github.ref_name}}
        draft: false
        prerelease: false
        files: |
          pixljs_all_${{matrix.board}}.hex
          pixjs_ota_v19_${{matrix.board}}.zip
          fw_readme.txt
          fw_update.bat
